platform:ios,’8.0’
target 'ConnectionCity' do
pod 'AFNetworking', '~> 3.0'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'SDWebImage', '~>3.8'
pod 'MJRefresh'
pod 'MJExtension'
pod 'IQKeyboardManager'
pod 'Masonry'
pod 'AMap2DMap'
pod 'AMapSearch'
pod 'AMapLocation'
pod 'FMDB'
pod 'MLLabel'
pod 'RongCloudIM/IMLib', '~> 2.8.3'
pod 'RongCloudIM/IMKit', '~> 2.8.3'
pod "Qiniu", "~> 7.1"
end

